# Change these first
owner: israelliebana # Your GitHub organization or username, where this repository lives
repo: upptime2 # The name of this repository

sites:
    - name: Cosmos Web Extranet Server (dev)
      url: https://dev.server.extranet.cosmosweb.cloud/api/v0/status
      headers:
          - "x-api-key: kU7QOzmqbGPsA6Mrl1SGTY"
          - "Content-Type: application/json"
    - name: Cosmos Web Extranet (dev)
      url: https://dev.extranet.cosmosweb.cloud/health
    - name: DevFlexWork (dev)
      url: https://dev.devflexwork.com/api/health
status-website:
    # Add your custom domain name, or remove the `cname` line if you don't have a domain
    # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
    #cname: demo.upptime.js.org
    baseUrl: /upptime2
    logoUrl: https://israelliebana.github.io/upptime2/cosmosweb-logo-v240w240h.avif
    favicon: https://israelliebana.github.io/upptime2/cosmosweb-logo-v240w240h.avif
    name: Cosmos Web - Monitorizaci칩n
    introTitle: "P치gina de estado"
    introMessage: Informaci칩n en tiempo real
    navbar:
        - title: Estado
          href: /upptime2
    themeUrl: https://israelliebana.github.io/upptime2/custom-theme.css
    links:
        - rel: stylesheet
          href: https://israelliebana.github.io/upptime2/custom-styles.css
i18n:
    footer: Cosmos Web - Monitorizaci칩n
    activeIncidents: Incidentes activos
    allSystemsOperational: Todos los sistemas est치n operativos
    url: "URL"
    status: "Estado"
    history: "Hist칩rico"
    uptime: "Tiempo de actividad total"
    up: "游릴 Disponible"
    degraded: "游릳 Degradedo"
    down: "游린 No disponible"
    responseTimeGraphAlt: "Gr치fico de tiempos de respuesta"
    ms: "ms"
    responseTime: "Tiempo de respuesta"
    responseTimeDay: "Tiempo de respuesta de 24 horas"
    responseTimeWeek: "Tiempo de respuesta de 7 d칤as"
    responseTimeMonth: "Tiempo de respuesta de 30 d칤as"
    responseTimeYear: "Tiempo de respuesta de 1 a침o"
    uptimeDay: "Tiempo de actividad durante 24 horas"
    uptimeWeek: "Tiempo de actividad durante 7 d칤as"
    uptimeMonth: "Tiempo de actividad durante 30 d칤as"
    uptimeYear: "Tiempo de actividad durante 1 a침o"
    liveStatus: "Estado en vivo"
    liveStatusHtmlComment: "<!-- estado en vivo -->"
    degradedPerformance: "游릳 Rendimiento degradado"
    completeOutage: "游린 Corte completo"
    partialOutage: "游릲 Corte parcial"
